modgroup=com.melodiccougar7.immersivefixes
modarchivename=immersivefixes
mod_version=1.2.0
mod_id=immersivefixes
mod_name=Immersive Fixes 1.12.2
mod_authors=MelodicCougar7
mod_logo=ImmersiveFixes_logo.png
mod_description=1.12.2 IE addon that backports critical bug fixes and minor content. This is a separate project from 1.20.1 IFx and will not always address the same problem with the same fixes.
