org.gradle.jvmargs = -Xmx3G

use_modern_java_syntax = false
use_jetbrains_annotations = false
generate_sources_jar = true
generate_javadocs_jar = false

mod_version = 1.1.2
root_package = com.melodiccougar7
mod_id = immersivefixes
mod_name = Immersive Fixes 1.12.2
mod_description = 1.12.2 IE addon that backports critical bug fixes and minor content. This is a separate project from 1.20.1 IFx and will not always address the same problem with the same fixes.
mod_url =
mod_update_json =
mod_authors = MelodicCougar7
mod_credits =
mod_logo_path = resources/ImmersiveFixes_logo.png

mapping_channel = stable
mapping_version = 39
use_dependency_at_files = true

minecraft_username = Developer
extra_jvm_args =
extra_tweak_classes =
change_minecraft_sources = false

publish_to_maven = false
publish_to_curseforge = false
publish_to_modrinth = false

use_tags = true
tag_class_name = ${root_package}.${mod_id}.Tags

use_access_transformer = false

use_mixins = true
mixin_booter_version = 10.7
mixin_configs = ${mod_id}
mixin_refmap = mixins.${mod_id}.refmap.json

is_coremod = false

use_asset_mover = false
